#!/usr/bin/env python3
"""HANDOFF_REPORT.md + tables for a v02_handoff_exp.py result (numbers derived, not transcribed).

    python3 scripts/v02_handoff_report.py RESULT_DIR OUT_DIR
"""
from __future__ import annotations

import csv
import json
import statistics as st
import sys
from pathlib import Path


def cpu(t):
    return (t.get("utime_s") or 0) + (t.get("stime_s") or 0)


def ci(s, unit=" ms"):
    return f"{s['median']:+.2f}{unit} ({s['median_ci90'][0]:+.2f}..{s['median_ci90'][1]:+.2f})"


def main() -> int:
    src, outdir = Path(sys.argv[1]), Path(sys.argv[2])
    r = json.loads((src / "handoff.json").read_text())
    R = r["rounds"]
    meas = [x for x in R["rows"] if not x["warmup"]]
    (outdir / "tables").mkdir(parents=True, exist_ok=True)

    def metrics(mode):
        col = [x[mode]["collector"] for x in meas]
        g = lambda f: st.median(f(c) for c in col)
        return {"records_received": g(lambda c: c["stats"]["received"]), "records_submitted": g(lambda c: c["stats"]["submitted"]),
                "queue_handoffs": g(lambda c: c["queue"]["puts"]), "records_handed_off": g(lambda c: c["queue"]["put_records"]),
                "writer_gets": g(lambda c: c["queue"]["gets"]), "writer_blocked_on_empty_queue": g(lambda c: c["queue"]["get_waited"]),
                "queue_high_water_items": max(c["queue"]["high_water_items"] for c in col),
                "collector_vol_ctx": g(lambda c: c["self"]["vol_ctx"]), "collector_invol_ctx": g(lambda c: c["self"]["invol_ctx"]),
                "writer_thread_vol_ctx": g(lambda c: c["threads"]["writer"].get("vol_ctx", 0)),
                "consumer_thread_vol_ctx": g(lambda c: c["threads"]["ring_consumer"].get("vol_ctx", 0)),
                "collector_cpu_s": g(lambda c: cpu(c["self"])), "consumer_thread_cpu_s": g(lambda c: cpu(c["threads"]["ring_consumer"])),
                "writer_thread_cpu_s": g(lambda c: cpu(c["threads"]["writer"])), "store_worker_cpu_s": g(lambda c: cpu(c["store"])),
                "store_bytes_written": g(lambda c: c["store"].get("write_bytes", 0)),
                "sqlite_ingest_ms": g(lambda c: c["counters"]["ingest_ns"] / 1e6), "sqlite_commits": g(lambda c: c["writer_batches"]),
                "kernel_drops": sum(c["kernel_drops"] for c in col), "queue_drops": sum(c["stats"]["queue_drops"] for c in col),
                "workload_invol_ctx": st.median(x[mode]["wl_invol_ctx"] for x in meas)}

    B, Eb, Ea = metrics("B"), metrics("Eb"), metrics("Ea")
    lat = r["latency"]
    derived = {"source": str(src), "git_after": r["git"]["head"], "before_tree": r["params"]["before_tree_head"],
               "rounds": len(meas), "timing_ms": {k: R[k] for k in ("B_minus_A", "Eb_minus_A", "Ea_minus_A", "Eb_minus_B", "Ea_minus_B", "Eb_minus_Ea")},
               "overhead_pct": R["overhead_pct"], "kernel_only": B, "before": Eb, "after": Ea,
               "latency": {t: {k: {kk: vv for kk, vv in v.items()} for k, v in L.items()} for t, L in lat.items()},
               "hypothesis": ("rejected" if R["Eb_minus_Ea"]["median_ci90"][0] <= 0 <= R["Eb_minus_Ea"]["median_ci90"][1]
                              or R["Eb_minus_Ea"]["median"] < 1.0 else "supported")}
    (outdir / "derived.json").write_text(json.dumps(derived, indent=2))
    with (outdir / "tables" / "rounds.csv").open("w", newline="") as fh:
        w = csv.writer(fh)
        w.writerow(["round", "warmup", "order", "A_ms", "B_ms", "Eb_ms", "Ea_ms"])
        for i, x in enumerate(R["rows"]):
            w.writerow([i, x["warmup"], "/".join(x["order"])] + [x[m]["s"] * 1000 for m in ("A", "B", "Eb", "Ea")])
    with (outdir / "tables" / "collector_metrics.csv").open("w", newline="") as fh:
        w = csv.writer(fh)
        w.writerow(["metric", "kernel_only_B", "before_Eb", "after_Ea"])
        for k in Eb:
            w.writerow([k, B[k], Eb[k], Ea[k]])
    with (outdir / "tables" / "latency_samples.csv").open("w", newline="") as fh:
        w = csv.writer(fh)
        w.writerow(["version", "condition", "sample", "latency_ms"])
        for t, L in lat.items():
            for cond, v in L.items():
                for i, s in enumerate(v["samples_ms"]):
                    w.writerow([t, cond, i, s])

    def pct(a, b):
        return f"{(b / a - 1) * 100:+.0f}%" if a else "—"

    L = []
    A = L.append
    A("# whyfs v0.2 — batched writer handoff: before/after")
    A("")
    A("**Standing verdict: V0.2 PERFORMANCE GATE REMAINS FAILED.** Graduation was not rerun: this change did not produce a clear win.")
    A("Generated by `scripts/v02_handoff_report.py` from the raw `handoff.json`.")
    A("")
    A("## Question and answer")
    A("")
    A("*Does replacing ~3,000 per-record writer handoffs with ordered batches materially remove the userspace portion of")
    A("whyfs's static-workload overhead?*")
    A("")
    A(f"**No.** Handoffs per run fell from {Eb['queue_handoffs']:,.0f} to {Ea['queue_handoffs']:,.0f}, collector voluntary context "
      f"switches from {Eb['collector_vol_ctx']:,.0f} to {Ea['collector_vol_ctx']:,.0f} ({pct(Eb['collector_vol_ctx'], Ea['collector_vol_ctx'])}), "
      f"and collector CPU from {Eb['collector_cpu_s']:.3f} s to {Ea['collector_cpu_s']:.3f} s ({pct(Eb['collector_cpu_s'], Ea['collector_cpu_s'])}). "
      f"But the static ×300 workload's added time moved by **{ci(R['Eb_minus_Ea'])}** "
      f"(before − after): **not a measurable change**. The wakeup hypothesis is **{derived['hypothesis']}** (kill condition).")
    A("")
    A("## Method")
    A("")
    A(f"- Two separate collector processes run the production path wired exactly as the daemon wires it (BCCCollector + privilege-separated Store).")
    A(f"  - **before** runs tree `{r['params']['before_tree_head'][:7]}` (per-record handoff; its `src/` is identical to the frozen candidate a5f4746).")
    A(f"  - **after** runs `{r['git']['head'][:7]}` (batched handoff).")
    A("  - The BPF programs are identical; the two collectors are attached one at a time.")
    A(f"- **{len(meas)} rotated rounds** over A (baseline), B (kernel only), Eb (before, full), Ea (after, full): 8 orders, plus 1 warm-up round.")
    A("  Before and after are interleaved in the same rounds, so time drift cannot separate them.")
    A("- The workload is exactly the graduation harness's static ×300, **timed inside its own shell**.")
    A("- Collector metrics come from `/proc` (process and per-thread) and from queue counters observing the handoff.")
    A("")
    A("## Step 1: the current handoff path (confirmed in code and measurement)")
    A("")
    A("The ring-buffer callback (`BCCCollector._process_event`, on the consumer thread) normalizes each event.")
    A("")
    A("**Before:** `_put()` called `queue.put_nowait(record)` once **per record**. The SQLite writer thread (`BatchWriter.run`)")
    A("took records one `queue.get()` at a time, and committed through the privilege-separated store in batches of up to 512")
    A("rows or every 100 ms.")
    A("")
    A(f"Measured: {Eb['queue_handoffs']:,.0f} handoffs and {Eb['writer_gets']:,.0f} writer `get()` calls per run. The writer was actually")
    A(f"blocked on an empty queue only {Eb['writer_blocked_on_empty_queue']:,.0f} times. Its {Eb['writer_thread_vol_ctx']:,.0f} voluntary context")
    A("switches come from contention on the queue lock and the GIL with the consumer thread on every per-record `get`/`put`,")
    A("not from empty-queue wakeups.")
    A("")
    A("**After:** `_put()` appends to an ordered local list. `flush_pending()` hands the list over as **one queue item** at the end")
    A("of every ring-buffer drain (`poll`/`drain`/`stop`), or when it reaches `HANDOFF_BATCH` = 512 records.")
    A("")
    A("- The queue is bounded at `QUEUE_RECORDS // HANDOFF_BATCH` batches, the same 262,144-record bound as before.")
    A("- A full queue drops that batch and counts every record in it in `queue_drops`.")
    A("- The writer accepts lists and single records.")
    A("- The flush happens once per drain, so no record waits longer than one poll interval, as before.")
    A("")
    A("## Results (per 300-process run; medians; 90% CI)")
    A("")
    A("| Metric | Before (per-record) | After (batched) | Change |")
    A("|---|---|---|---|")
    rows = [("records received", "records_received", "{:,.0f}"), ("records submitted", "records_submitted", "{:,.0f}"),
            ("queue handoffs", "queue_handoffs", "{:,.0f}"), ("writer `get()` calls", "writer_gets", "{:,.0f}"),
            ("writer blocked on empty queue", "writer_blocked_on_empty_queue", "{:,.0f}"),
            ("queue high-water (items)", "queue_high_water_items", "{:,.0f}"),
            ("collector voluntary context switches", "collector_vol_ctx", "{:,.0f}"),
            ("… writer thread", "writer_thread_vol_ctx", "{:,.0f}"), ("… ring-consumer thread", "consumer_thread_vol_ctx", "{:,.0f}"),
            ("collector CPU (s)", "collector_cpu_s", "{:.3f}"), ("… ring-consumer thread CPU (s)", "consumer_thread_cpu_s", "{:.3f}"),
            ("… writer thread CPU (s)", "writer_thread_cpu_s", "{:.3f}"), ("store worker CPU (s)", "store_worker_cpu_s", "{:.3f}"),
            ("store bytes written", "store_bytes_written", "{:,.0f}"), ("SQLite ingest time (ms)", "sqlite_ingest_ms", "{:.1f}"),
            ("SQLite commits", "sqlite_commits", "{:,.0f}"), ("kernel drops (sum)", "kernel_drops", "{:,.0f}"),
            ("queue drops (sum)", "queue_drops", "{:,.0f}"), ("workload involuntary ctx switches", "workload_invol_ctx", "{:,.0f}")]
    for lab, k, f in rows:
        A(f"| {lab} | {f.format(Eb[k])} | {f.format(Ea[k])} | {pct(Eb[k], Ea[k]) if isinstance(Eb[k], (int, float)) and Eb[k] else '—'} |")
    A("")
    A("| Workload timing | ms per run (90% CI) |")
    A("|---|---|")
    A(f"| kernel BPF + ring consumption (B − A) | {ci(R['B_minus_A'])} |")
    A(f"| userspace processing + store, before (Eb − B) | {ci(R['Eb_minus_B'])} |")
    A(f"| userspace processing + store, after (Ea − B) | {ci(R['Ea_minus_B'])} |")
    A(f"| total added time, before (Eb − A) | {ci(R['Eb_minus_A'])} = {R['overhead_pct']['Eb']['median']:+.2f}% |")
    A(f"| total added time, after (Ea − A) | {ci(R['Ea_minus_A'])} = {R['overhead_pct']['Ea']['median']:+.2f}% |")
    A(f"| **before − after** | **{ci(R['Eb_minus_Ea'])}** |")
    A("")
    A("## Visibility latency (kernel event timestamp → row queryable in SQLite)")
    A("")
    A("| Version | Condition | Median | p95 | Max | Missing |")
    A("|---|---|---|---|---|---|")
    for t in ("before", "after"):
        for cond, lab in (("idle", "idle"), ("load", "during a static ×300 build")):
            v = lat[t][cond]
            A(f"| {t} | {lab} | {v['median_ms']:.1f} ms | {v['p95_ms']:.1f} ms | {v['max_ms']:.1f} ms | {v['missing']} |")
    A("")
    A("Batching does not change visibility latency. The absolute values (~200–300 ms) are measured as polling time minus the")
    A("event's recorded timestamp. That timestamp is the kernel's monotonic time converted to wall clock by the collector, and")
    A("the conversion was not independently validated, so treat the absolute level as approximate. The before/after comparison")
    A("uses the same conversion and is unaffected.")
    A("")
    A("## Decision")
    A("")
    A("- **Hypothesis rejected.** Removing ~99.8% of handoffs and ~80% of collector context switches did not measurably reduce the")
    A("  workload's added time. The per-record handoff was *collector* overhead, not a cause of workload slowdown.")
    A(f"- **Change retained**, as an engineering improvement to the always-on collector: {pct(Eb['collector_cpu_s'], Ea['collector_cpu_s'])} "
      f"collector CPU and {pct(Eb['collector_vol_ctx'], Ea['collector_vol_ctx'])} context switches, with identical record counts,")
    A("  zero drops and unchanged latency. It is covered by new regression tests: order across batches, partial batch flushed on")
    A("  stop, full-queue drop accounting, writer-failure propagation, memory bound, and identical lineage batched vs per-record.")
    A("  **It is not a performance-gate improvement and is not claimed as one.**")
    A("- **No graduation rerun** (no clear win, per protocol). No further optimization in this session.")
    A(f"- **Remaining measured static ×300 cost:** kernel ≈ {R['B_minus_A']['median']:.1f} ms, userspace processing + store ≈ "
      f"{R['Ea_minus_B']['median']:.1f} ms. The userspace part does not come from handoff wakeups; its mechanism is still unidentified.")
    A("")
    A("## Separate known-noise issue (not addressed here)")
    A("")
    A("Each daemon start records one provenance event of its own: the atomic replace of `.whyfs/daemon.json` inside the")
    A("watched workspace (see `results/v02-daemon-gap/DAEMON_GAP_REPORT.md`). It is deliberately not bundled with this change.")
    (outdir / "HANDOFF_REPORT.md").write_text("\n".join(L) + "\n")
    print("\n".join(L))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
